fragment LineItemFields on CartLine {
	id
	__typename
	quantity
	cost {
		__typename
		totalAmount {
			amount
			currencyCode
		}
	}
	merchandise {
		__typename
		... on ProductVariant {
			__typename
			id
			title
			product {
				__typename
				id
				title
				vendor
			}
			image {
				__typename
				id
				url(transform: { maxHeight: 128, maxWidth: 128, scale: 2 })
				altText
				width
				height
			}
			priceV2 {
				__typename
				amount
				currencyCode
			}
		}
	}
}
